from datetime import date, datetime

import pyspark.sql.types as T
import pytest
from dotenv import load_dotenv
from pyspark.sql import SparkSession
from pyspark.testing.utils import assertDataFrameEqual

from spark_flights_etl.etl import Featurizer


@pytest.fixture
def spark_fixture():
    # Carga la variables de congiración para ejecutar PySpark en local
    load_dotenv()

    spark = SparkSession.builder.appName("Testing PySpark Example").getOrCreate()
    yield spark


def test_featurizer(spark_fixture):
    sample_data = [
        (
            4,
            8,
            7,
            date(2018, 4, 8),
            "MSP",
            "Minneapolis, MN",
            "BJI",
            "Bemidji, MN",
            2200,
            -5.00,
            2325,
            16.00,
            0.00,
            "",
            0.00,
            85.00,
            37.00,
            199.00,
            0.00,
            0.00,
            16.00,
            0.00,
            0.00,
        ),
        (
            4,
            23,
            1,
            date(2018, 4, 23),
            "PHX",
            "Phoenix, AZ",
            "ORD",
            "Chicago, IL",
            715,
            -5.00,
            1231,
            -14.00,
            0.00,
            "",
            0.00,
            196.00,
            176.00,
            1440.00,
            None,
            None,
            None,
            None,
            None,
        ),
        (
            3,
            28,
            3,
            date(2018, 3, 28),
            "DFW",
            "Dallas/Fort Worth, TX",
            "MLU",
            "Monroe, LA",
            1429,
            -6.00,
            1541,
            -2.00,
            0.00,
            "",
            0.00,
            72.00,
            48.00,
            293.00,
            None,
            None,
            None,
            None,
            None,
        ),
        (
            3,
            17,
            6,
            date(2018, 3, 17),
            "ECP",
            "Panama City, FL",
            "IAH",
            "Houston, TX",
            1424,
            -8.00,
            1638,
            0.00,
            0.00,
            "",
            0.00,
            134.00,
            110.00,
            572.00,
            None,
            None,
            None,
            None,
            None,
        ),
        (
            4,
            27,
            5,
            date(2018, 4, 27),
            "LGB",
            "Long Beach, CA",
            "SMF",
            "Sacramento, CA",
            1644,
            4.00,
            1758,
            -8.00,
            0.00,
            "",
            0.00,
            74.00,
            61.00,
            387.00,
            None,
            None,
            None,
            None,
            None,
        ),
    ]
    schema = T.StructType(
        [
            T.StructField("Month", T.IntegerType(), True),
            T.StructField("DayofMonth", T.IntegerType(), True),
            T.StructField("DayOfWeek", T.IntegerType(), True),
            T.StructField("FlightDate", T.DateType(), True),
            T.StructField("Origin", T.StringType(), True),
            T.StructField("OriginCity", T.StringType(), True),
            T.StructField("Dest", T.StringType(), True),
            T.StructField("DestCity", T.StringType(), True),
            T.StructField("DepTime", T.IntegerType(), True),
            T.StructField("DepDelay", T.DoubleType(), True),
            T.StructField("ArrTime", T.IntegerType(), True),
            T.StructField("ArrDelay", T.DoubleType(), True),
            T.StructField("Cancelled", T.DoubleType(), True),
            T.StructField("CancellationCode", T.StringType(), True),
            T.StructField("Diverted", T.DoubleType(), True),
            T.StructField("ActualElapsedTime", T.DoubleType(), True),
            T.StructField("AirTime", T.DoubleType(), True),
            T.StructField("Distance", T.DoubleType(), True),
            T.StructField("CarrierDelay", T.DoubleType(), True),
            T.StructField("WeatherDelay", T.DoubleType(), True),
            T.StructField("NASDelay", T.DoubleType(), True),
            T.StructField("SecurityDelay", T.DoubleType(), True),
            T.StructField("LateAircraftDelay", T.DoubleType(), True),
        ]
    )
    original_df = spark_fixture.createDataFrame(sample_data, schema=schema)

    transformed_df = Featurizer.preprocesa(original_df)

    # Crear un DataFrame esperado con los resultados esperados
    expected_data = [
        (
            4,
            8,
            7,
            date(2018, 4, 8),
            "MSP",
            "Minneapolis, MN",
            "BJI",
            "Bemidji, MN",
            2200,
            -5.0,
            2325,
            16.0,
            0.0,
            "",
            False,
            85.0,
            37.0,
            199.0,
            0.0,
            0.0,
            16.0,
            0.0,
            0.0,
            datetime(2018, 4, 8, 22, 0, 0),
        ),
        (
            4,
            23,
            1,
            date(2018, 4, 23),
            "PHX",
            "Phoenix, AZ",
            "ORD",
            "Chicago, IL",
            715,
            -5.0,
            1231,
            -14.0,
            0.0,
            "",
            False,
            196.0,
            176.0,
            1440.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            datetime(2018, 4, 23, 7, 15, 0),
        ),
        (
            3,
            28,
            3,
            date(2018, 3, 28),
            "DFW",
            "Dallas/Fort Worth, TX",
            "MLU",
            "Monroe, LA",
            1429,
            -6.0,
            1541,
            -2.0,
            0.0,
            "",
            False,
            72.0,
            48.0,
            293.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            datetime(2018, 3, 28, 14, 29, 0),
        ),
        (
            3,
            17,
            6,
            date(2018, 3, 17),
            "ECP",
            "Panama City, FL",
            "IAH",
            "Houston, TX",
            1424,
            -8.0,
            1638,
            0.0,
            0.0,
            "",
            False,
            134.0,
            110.0,
            572.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            datetime(2018, 3, 17, 14, 24, 0),
        ),
        (
            4,
            27,
            5,
            date(2018, 4, 27),
            "LGB",
            "Long Beach, CA",
            "SMF",
            "Sacramento, CA",
            1644,
            4.0,
            1758,
            -8.0,
            0.0,
            "",
            False,
            74.0,
            61.0,
            387.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            datetime(2018, 4, 27, 16, 44, 0),
        ),
    ]
    expected_schema = T.StructType(
        [
            f
            if f.name != "Diverted"
            else T.StructField("Diverted", T.BooleanType(), True)
            for f in schema.fields
        ]
        + [T.StructField("FlightTs", T.TimestampType(), True)]
    )
    expected_df = spark_fixture.createDataFrame(expected_data, schema=expected_schema)

    # Comparar los DataFrames resultante y esperado
    assertDataFrameEqual(transformed_df, expected_df)
